[muon]
num_lanes = 16
num_warps = 4
num_cores = 1
num_regs = 256
# vecadd.elf .text VMA: 0x80000000
# pathtracer.elf .text VMA: 0x80000000
start_pc = 0x80000000
smem_size = 65536

[mem]
io_cout_addr = 0xFF080000
io_cout_size = 64

[sim]
elf = "test/pathtracer.elf"
timeout = 5000000
trace = false

[timing]
include = [
  "config/timing/gmem_nodes.toml",
  "config/timing/gmem_links.toml",
  "config/timing/gmem_policy.toml",
  "config/timing/icache.toml",
  "config/timing/lsu.toml",
  "config/timing/operand_fetch.toml",
  "config/timing/scheduler.toml",
  "config/timing/smem_nodes.toml",
  "config/timing/smem_topology.toml",
  "config/timing/writeback.toml",
  "config/timing/barrier.toml",
  "config/timing/fence.toml",
  "config/timing/dma.toml",
  "config/timing/tensor.toml",
  "config/timing/execute.toml",
]
