[execute.alu]
base_latency = 1
bytes_per_cycle = 16
queue_capacity = 4
completions_per_cycle = 1

[execute.int_mul]
base_latency = 3
bytes_per_cycle = 16
queue_capacity = 2
completions_per_cycle = 1

[execute.int_div]
base_latency = 16
bytes_per_cycle = 8
queue_capacity = 2
completions_per_cycle = 1

[execute.fp]
base_latency = 4
bytes_per_cycle = 8
queue_capacity = 4
completions_per_cycle = 1

[execute.sfu]
base_latency = 8
bytes_per_cycle = 16
queue_capacity = 2
completions_per_cycle = 1
