[gmem]
# Cache levels are fully config-driven via `gmem.levels`.

[[gmem.levels]]
banks = 1

[gmem.levels.tag]
base_latency = 1
bytes_per_cycle = 64
queue_capacity = 8

[gmem.levels.data]
base_latency = 2
bytes_per_cycle = 64
queue_capacity = 8

[gmem.levels.mshr]
base_latency = 1
bytes_per_cycle = 64
queue_capacity = 8

[[gmem.levels]]
banks = 2

[gmem.levels.tag]
base_latency = 2
bytes_per_cycle = 64
queue_capacity = 16

[gmem.levels.data]
base_latency = 6
bytes_per_cycle = 64
queue_capacity = 16

[gmem.levels.mshr]
base_latency = 1
bytes_per_cycle = 64
queue_capacity = 8

[gmem.levels.refill]
base_latency = 4
bytes_per_cycle = 32
queue_capacity = 16

[gmem.levels.writeback]
base_latency = 2
bytes_per_cycle = 32
queue_capacity = 8

[[gmem.levels]]
banks = 1

[gmem.levels.tag]
base_latency = 4
bytes_per_cycle = 64
queue_capacity = 16

[gmem.levels.data]
base_latency = 6
bytes_per_cycle = 64
queue_capacity = 16

[gmem.levels.mshr]
base_latency = 1
bytes_per_cycle = 64
queue_capacity = 8

[gmem.levels.refill]
base_latency = 8
bytes_per_cycle = 32
queue_capacity = 16

[gmem.levels.writeback]
base_latency = 4
bytes_per_cycle = 32
queue_capacity = 8

[gmem.nodes.coalescer]
base_latency = 1
bytes_per_cycle = 64
queue_capacity = 16

[gmem.nodes.l0_flush_gate]
base_latency = 0
bytes_per_cycle = 64
queue_capacity = 4

[gmem.nodes.l1_flush_gate]
base_latency = 0
bytes_per_cycle = 64
queue_capacity = 4

[gmem.nodes.dram]
# Adjustable default values per request
base_latency = 200
bytes_per_cycle = 32
queue_capacity = 64

[gmem.nodes.return_path]
base_latency = 0
bytes_per_cycle = 1024
queue_capacity = 128
