[smem]
num_banks = 8
num_lanes = 16
num_subbanks = 1
word_bytes = 4
serialize_cores = false
link_capacity = 1024

[smem.lane]
base_latency = 1
bytes_per_cycle = 1024
queue_capacity = 1024
completions_per_cycle = 1024

[smem.serial]
base_latency = 1
bytes_per_cycle = 1024
queue_capacity = 1024
completions_per_cycle = 1024

[smem.crossbar]
base_latency = 1
bytes_per_cycle = 1024
queue_capacity = 1024
completions_per_cycle = 1024

[smem.subbank]
base_latency = 1
bytes_per_cycle = 1024
queue_capacity = 1024
completions_per_cycle = 1024

[smem.bank]
base_latency = 1
bytes_per_cycle = 1024
queue_capacity = 1024
completions_per_cycle = 1024
