# GMEM L2 miss isolation profile

[gmem.policy]
l0_enabled = true

[[gmem.levels]]
banks = 1

[gmem.levels.tag]
base_latency = 1
bytes_per_cycle = 64
queue_capacity = 4096
completions_per_cycle = 4096

[gmem.levels.data]
base_latency = 1
bytes_per_cycle = 64
queue_capacity = 4096
completions_per_cycle = 4096

[gmem.levels.mshr]
base_latency = 1
bytes_per_cycle = 64
queue_capacity = 4096
completions_per_cycle = 4096

[[gmem.levels]]
banks = 2

[gmem.levels.tag]
base_latency = 1
bytes_per_cycle = 64
queue_capacity = 4096
completions_per_cycle = 4096

[gmem.levels.data]
base_latency = 1
bytes_per_cycle = 64
queue_capacity = 4096
completions_per_cycle = 4096

[gmem.levels.mshr]
base_latency = 1
bytes_per_cycle = 64
queue_capacity = 4096
completions_per_cycle = 4096

[gmem.levels.refill]
base_latency = 1
bytes_per_cycle = 64
queue_capacity = 4096
completions_per_cycle = 4096

[gmem.levels.writeback]
base_latency = 1
bytes_per_cycle = 64
queue_capacity = 4096
completions_per_cycle = 4096

[[gmem.levels]]
banks = 1

[gmem.levels.tag]
base_latency = 4
bytes_per_cycle = 64
queue_capacity = 4096
completions_per_cycle = 4096

[gmem.levels.data]
base_latency = 6
bytes_per_cycle = 64
queue_capacity = 4096
completions_per_cycle = 4096

[gmem.levels.mshr]
base_latency = 1
bytes_per_cycle = 64
queue_capacity = 4096
completions_per_cycle = 4096

[gmem.levels.refill]
base_latency = 1
bytes_per_cycle = 64
queue_capacity = 4096
completions_per_cycle = 4096

[gmem.levels.writeback]
base_latency = 1
bytes_per_cycle = 64
queue_capacity = 4096
completions_per_cycle = 4096

[gmem.nodes.coalescer]
base_latency = 0
bytes_per_cycle = 1024
queue_capacity = 1024
completions_per_cycle = 1024

[gmem.nodes.l0_flush_gate]
base_latency = 0
bytes_per_cycle = 1024
queue_capacity = 1024
completions_per_cycle = 1024

[gmem.nodes.l1_flush_gate]
base_latency = 0
bytes_per_cycle = 1024
queue_capacity = 1024
completions_per_cycle = 1024

[gmem.nodes.dram]
base_latency = 1000
bytes_per_cycle = 32
queue_capacity = 64
completions_per_cycle = 1

[gmem.nodes.return_path]
base_latency = 0
bytes_per_cycle = 1024
queue_capacity = 1024
completions_per_cycle = 1024

[lsu]
link_capacity = 1024

[lsu.resources]
address_entries = 1024
store_data_entries = 1024
load_data_entries = 1024

[lsu.queues.global_ldq]
queue_capacity = 1024
bytes_per_cycle = 1024
base_latency = 0
completions_per_cycle = 1024

[lsu.queues.global_stq]
queue_capacity = 1024
bytes_per_cycle = 1024
base_latency = 0
completions_per_cycle = 1024

[lsu.queues.shared_ldq]
queue_capacity = 1024
bytes_per_cycle = 1024
base_latency = 0
completions_per_cycle = 1024

[lsu.queues.shared_stq]
queue_capacity = 1024
bytes_per_cycle = 1024
base_latency = 0
completions_per_cycle = 1024

[lsu.issue]
queue_capacity = 1024
bytes_per_cycle = 1024
base_latency = 0
completions_per_cycle = 1024

[smem]
num_banks = 4
num_lanes = 16
num_subbanks = 4
word_bytes = 4
serialize_cores = true
link_capacity = 16

[smem.lane]
base_latency = 0
bytes_per_cycle = 1024
queue_capacity = 1024
completions_per_cycle = 1024

[smem.serial]
base_latency = 0
bytes_per_cycle = 1024
queue_capacity = 1024
completions_per_cycle = 1024

[smem.crossbar]
base_latency = 0
bytes_per_cycle = 1024
queue_capacity = 1024
completions_per_cycle = 1024

[smem.subbank]
base_latency = 0
bytes_per_cycle = 1024
queue_capacity = 1024
completions_per_cycle = 1024

[smem.bank]
base_latency = 0
bytes_per_cycle = 1024
queue_capacity = 1024
completions_per_cycle = 1024

[execute.alu]
base_latency = 0
bytes_per_cycle = 1024
queue_capacity = 1024
completions_per_cycle = 1024
